<?php

/**
 * @package Jollyany Addons SP Page Builder
 * @author TemPlaza https://templaza.com
 * @copyright Copyright (c) 2011 - 2021 TemPlaza
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or later
 */
//no direct accees
defined('_JEXEC') or die('Restricted access');
SpAddonsConfig::addonConfig(
    array(
      'type' => 'general',
      'addon_name' => 'uinavbar',
      'title' => \Joomla\CMS\Language\Text::_('UI Navbar'),
      'desc' => \Joomla\CMS\Language\Text::_('Create a navigation bar that can be used for your main site navigation.'),
      'icon'=>\Joomla\CMS\Uri\Uri::root() . 'plugins/sppagebuilder/jollyany/addons/uinavbar/assets/images/icon.png',
      'category' => 'Jollyany',
      'attr' => array(
          'general' => array(
            'admin_label' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_ADMIN_LABEL'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_ADMIN_LABEL_DESC'),
                'std' => ''
            ),
            'title_addon' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('Add-on Title'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_TITLE_DESC'),
                'std' =>  '',
            ),
            'title_heading_style' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Style'),
                'desc' => \Joomla\CMS\Language\Text::_('Heading styles differ in font-size but may also come with a predefined color, size and font'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'heading-2xlarge' => \Joomla\CMS\Language\Text::_('2XLarge'),
                    'heading-xlarge' => \Joomla\CMS\Language\Text::_('XLarge'),
                    'heading-large' => \Joomla\CMS\Language\Text::_('Large'),
                    'heading-medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'heading-small' => \Joomla\CMS\Language\Text::_('Small'),
                    'h1' => \Joomla\CMS\Language\Text::_('H1'),
                    'h2' => \Joomla\CMS\Language\Text::_('H2'),
                    'h3' => \Joomla\CMS\Language\Text::_('H3'),
                    'h4' => \Joomla\CMS\Language\Text::_('H4'),
                    'h5' => \Joomla\CMS\Language\Text::_('H5'),
                    'h6' => \Joomla\CMS\Language\Text::_('H6'),
                ),
                'std' => 'h3',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_margin' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Title Margin'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the vertical margin for title.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Keep existing'),
                    'uk-margin-small' => \Joomla\CMS\Language\Text::_('Small'),
                    'uk-margin' => \Joomla\CMS\Language\Text::_('Default'),
                    'uk-margin-medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'uk-margin-large' => \Joomla\CMS\Language\Text::_('Large'),
                    'uk-margin-xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    'uk-margin-remove-vertical' => \Joomla\CMS\Language\Text::_('None'),
                ),
                'std' => 'uk-margin',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_decoration' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Decoration'),
                'desc' => \Joomla\CMS\Language\Text::_('Decorate the heading with a divider, bullet or a line that is vertically centered to the heading'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'uk-heading-divider' => \Joomla\CMS\Language\Text::_('Divider'),
                    'uk-heading-bullet' => \Joomla\CMS\Language\Text::_('Bullet'),
                    'uk-heading-line' => \Joomla\CMS\Language\Text::_('Line'),
                ),
                'std' => '',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_color' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Color'),
                'desc' => \Joomla\CMS\Language\Text::_('Select the text color. If the Background option is selected, styles that don\'t apply a background image use the primary color instead.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'text-muted' => \Joomla\CMS\Language\Text::_('Muted'),
                    'text-emphasis' => \Joomla\CMS\Language\Text::_('Emphasis'),
                    'text-primary' => \Joomla\CMS\Language\Text::_('Primary'),
                    'text-secondary' => \Joomla\CMS\Language\Text::_('Secondary'),
                    'text-success' => \Joomla\CMS\Language\Text::_('Success'),
                    'text-warning' => \Joomla\CMS\Language\Text::_('Warning'),
                    'text-danger' => \Joomla\CMS\Language\Text::_('Danger'),
                    'text-background' => \Joomla\CMS\Language\Text::_('Background'),
                ),
                'std' => '',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_selector' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('HTML Element'),
                'desc' => \Joomla\CMS\Language\Text::_('Choose one of the seven heading elements to fit your semantic structure.'),
                'values' => array(
                    'h1' => \Joomla\CMS\Language\Text::_('h1'),
                    'h2' => \Joomla\CMS\Language\Text::_('h2'),
                    'h3' => \Joomla\CMS\Language\Text::_('h3'),
                    'h4' => \Joomla\CMS\Language\Text::_('h4'),
                    'h5' => \Joomla\CMS\Language\Text::_('h5'),
                    'h6' => \Joomla\CMS\Language\Text::_('h6'),
                    'div' => \Joomla\CMS\Language\Text::_('div'),
                ),
                'std' => 'h3',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'image' => array(
                'type' => 'media',
                'title' => \Joomla\CMS\Language\Text::_('Logo'),
                'show_input' => true,
                'std' => ''
            ),
            'logo_position' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Logo Position'),
                'values' => array(
                    'left' => \Joomla\CMS\Language\Text::_('Left'),
                    'right' => \Joomla\CMS\Language\Text::_('Right'),
                ),
                'std' => 'left',
                'depends' => array(
                  array('image', '!=', ''),
                ),
            ),
            'alt_text' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_ALT_TEXT'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_ALT_TEXT_DESC'),
                'std' => 'Image',
                'depends' => array(
                  array('image', '!=', ''),
                ),
            ),
            'logo_margin' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Logo Margin'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the vertical margin for Logo.'),
                'values' => array(
                    '' => 'Keep existing',
                    'uk-margin-small' => 'Small',
                    'uk-margin' => 'Default',
                    'uk-margin-medium' => 'Medium',
                    'uk-margin-large' => 'Large',
                    'uk-margin-xlarge' => 'X-Large',
                    'uk-margin-remove-vertical' => 'None',
                ),
                'std' => '',
                'depends' => array(array('image', '!=', '')),
            ),
            'logo_link' => array(
                'type' => 'media',
                'format' => 'attachment',
                'hide_preview' => true,
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LINK'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LINK_DESC'),
                'std' => '',
                'depends' => array(
                  array('image', '!=', ''),
                ),
            ),

            'logo_link_target' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET_DESC'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET_SAME_WINDOW'),
                    '_blank' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET_NEW_WINDOW'),
                ),
                'depends' => array(
                  array('image', '!=', ''),
                ),
            ),
            'sp_link_list_item' => array(
              'title' => \Joomla\CMS\Language\Text::_('Items'),
              'attr' =>  array(
                'title' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('Menu item title'),
                    'std' => 'Home',
                ),
                'url' => array(
                    'type' => 'media',
                    'format' => 'attachment',
                    'hide_preview' => true,
                    'title' => \Joomla\CMS\Language\Text::_('Item URL'),
                    'placeholder' => 'http://',
                    'hide_preview' => true,
                ),
                'icon' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('Uikit Icons'),
                    'desc' => \Joomla\CMS\Language\Text::_('Place scalable vector icons anywhere in your content. See live preview here <a href="https://getuikit.com/docs/icon#library" target="_blank">https://getuikit.com/docs/icon</a>'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('Select an optional icon.'),
                        'home' => 'Home',
                        'sign-in' => 'Sign-in',
                        'sign-out' => 'Sign-out',
                        'user' => 'User',
                        'users' => 'Users',
                        'lock' => 'Lock',
                        'unlock' => 'Unlock',
                        'settings' => 'Settings',
                        'cog' => 'Cog',
                        'nut' => 'Nut',
                        'comment' => 'Comment',
                        'commenting' => 'Commenting',
                        'comments' => 'Comments',
                        'hashtag' => 'Hashtag',
                        'tag' => 'Tag',
                        'cart' => 'Cart',
                        'credit-card' => 'Credit-card',
                        'mail' => 'Mail',
                        'receiver' => 'Receiver',
                        'search' => 'Search',
                        'location' => 'Location',
                        'bookmark' => 'Bookmark',
                        'code' => 'Code',
                        'paint-bucket' => 'Paint-bucket',
                        'camera' => 'Camera',
                        'bell' => 'Bell',
                        'bolt' => 'Bolt',
                        'star' => 'Star',
                        'heart' => 'Heart',
                        'happy' => 'Happy',
                        'lifesaver' => 'Lifesaver',
                        'rss' => 'Rss',
                        'social' => 'Social',
                        'git-branch' => 'Git-branch',
                        'git-fork' => 'Git-fork',
                        'world' => 'World',
                        'calendar' => 'Calendar',
                        'clock' => 'Clock',
                        'history' => 'History',
                        'future' => 'Future',
                        'pencil' => 'Pencil',
                        'trash' => 'Trash',
                        'move' => 'Move',
                        'link' => 'Link',
                        'question' => 'Question',
                        'info' => 'Info',
                        'warning' => 'Warning',
                        'image' => 'Image',
                        'thumbnails' => 'Thumbnails',
                        'table' => 'Table',
                        'list' => 'List',
                        'menu' => 'Menu',
                        'grid' => 'Grid',
                        'more' => 'More',
                        'more-vertical' => 'More-vertical',
                        'plus' => 'Plus',
                        'plus-circle' => 'Plus-circle',
                        'minus' => 'Minus',
                        'minus-circle' => 'Minus-circle',
                        'close' => 'Close',
                        'check' => 'Check',
                        'ban' => 'Ban',
                        'refresh' => 'Refresh',
                        'play' => 'Play',
                        'play-circle' => 'Play-circle',
                        'tv' => 'Tv',
                        'desktop' => 'Desktop',
                        'laptop' => 'Laptop',
                        'tablet' => 'Tablet',
                        'phone' => 'Phone',
                        'tablet-landscape' => 'Tablet-landscape',
                        'phone-landscape' => 'Phone-landscape',
                        'file' => 'File',
                        'copy' => 'Copy',
                        'file-edit' => 'File-edit',
                        'folder' => 'Folder',
                        'album' => 'Album',
                        'push' => 'Push',
                        'pull' => 'Pull',
                        'server' => 'Server',
                        'database' => 'Database',
                        'cloud-upload' => 'Cloud-upload',
                        'cloud-download' => 'Cloud-download',
                        'download' => 'Download',
                        'upload' => 'Upload',
                        'reply' => 'Reply',
                        'forward' => 'Forward',
                        'expand' => 'Expand',
                        'shrink' => 'Shrink',
                        'arrow-up' => 'Arrow-up',
                        'arrow-down' => 'Arrow-down',
                        'arrow-left' => 'Arrow-left',
                        'arrow-right' => 'Arrow-right',
                        'chevron-up' => 'Chevron-up',
                        'chevron-down' => 'Chevron-down',
                        'chevron-left' => 'Chevron-left',
                        'chevron-right' => 'Chevron-right',
                        'triangle-up' => 'Triangle-up',
                        'triangle-down' => 'Triangle-down',
                        'triangle-left' => 'Triangle-left',
                        'triangle-right' => 'Triangle-right',
                        'bold' => 'Bold',
                        'italic' => 'Italic',
                        'strikethrough' => 'Strikethrough',
                        'video-camera' => 'Video-camera',
                        'quote-right' => 'Quote-right',
                        '500px' => '500px',
                        'behance' => 'Behance',
                        'dribbble' => 'Dribbble',
                        'facebook' => 'Facebook',
                        'flickr' => 'Flickr',
                        'foursquare' => 'Foursquare',
                        'github' => 'Github',
                        'github-alt' => 'Github-alt',
                        'gitter' => 'Gitter',
                        'google' => 'Google',
                        'google-plus' => 'Google-plus',
                        'instagram' => 'Instagram',
                        'joomla' => 'Joomla',
                        'linkedin' => 'Linkedin',
                        'pagekit' => 'Pagekit',
                        'pinterest' => 'Pinterest',
                        'soundcloud' => 'Soundcloud',
                        'tripadvisor' => 'Tripadvisor',
                        'tumblr' => 'Tumblr',
                        'twitter' => 'Twitter',
                        'uikit' => 'Uikit',
                        'etsy' => 'Etsy',
                        'vimeo' => 'Vimeo',
                        'whatsapp' => 'Whatsapp',
                        'wordpress' => 'Wordpress',
                        'xing' => 'Xing',
                        'yelp' => 'Yelp',
                        'youtube' => 'Youtube',
                        'print' => 'Print',
                        'reddit' => 'Reddit',
                        'file-text' => 'File Text',
                        'file-pdf' => 'File Pdf',
                        'chevron-double-left' => 'Chevron Double Left',
                        'chevron-double-right' => 'Chevron Double Right',
                    ),
                ),

                'active' => array(
                    'type' => 'checkbox',
                    'title' => \Joomla\CMS\Language\Text::_('Enable it to indicate an active menu item.'),
                    'std' => 0
                ),
                'target' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Link open'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('Self'),
                        '_blank' => \Joomla\CMS\Language\Text::_('New Window'),
                    ),
                ),
                'dropdown' => array(
                    'type' => 'textarea',
                    'title' => \Joomla\CMS\Language\Text::_('Dropdown content'),
                    'desc' => \Joomla\CMS\Language\Text::_('Custom dropdown content with special columns. Wrap your content inside a div to define the columns'),
                    'std' => '',
                    'depends' => array(array('title', '!=', '')),
                ),
                'dropdown_columns' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Dropdown columns'),
                    'values' => array(
                        '1' => \Joomla\CMS\Language\Text::_('1 Columns'),
                        '2' => \Joomla\CMS\Language\Text::_('2 Columns'),
                        '3' => \Joomla\CMS\Language\Text::_('3 Columns'),
                        '4' => \Joomla\CMS\Language\Text::_('4 Columns'),
                        '5' => \Joomla\CMS\Language\Text::_('5 Columns'),
                    ),
                    'std' => '2',
                    'depends' => array(array('title', '!=', '')),
                ),
                'item_class' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_CLASS'),
                    'std' => '',
                    'depends' => array(array('title', '!=', '')),
                ),
              )
            ),
            'separator_common_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Common'),
            ),
            'type' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Navigation Styles'),
                'desc' => \Joomla\CMS\Language\Text::_('Select navigation style for menu, you can use navbar type or nav type.'),
                'values' => array(
                    'uk-navbar-nav' => \Joomla\CMS\Language\Text::_('Navbar'),
                    'uk-nav uk-nav-default' => \Joomla\CMS\Language\Text::_('Nav'),
                ),
                'std' => 'uk-navbar-nav',
            ),
            'icon_position' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Icon position'),
                'values' => array(
                    'left' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LEFT'),
                    'right' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_RIGHT'),
                    'top' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_TOP'),
                ),
                'std' => 'left',
            ),
            'responsive_menu' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Toggle Menu'),
                'desc' => \Joomla\CMS\Language\Text::_('Check this option to create an icon as a toggle for offcanvas menu'),
                'std' => 1,
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'toggle_mode' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Toggle Mode'),
                'values' => array(
                    'slide' => \Joomla\CMS\Language\Text::_('Default'),
                    'push' => \Joomla\CMS\Language\Text::_('Push'),
                    'reveal' => \Joomla\CMS\Language\Text::_('Reveal'),
                    'none' => \Joomla\CMS\Language\Text::_('None'),
                ),
                'std' => 'slide',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'responsive_menu_class' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('Toggle Menu Class'),
                'desc' => \Joomla\CMS\Language\Text::_('You can use custom toggle menu class, i.e uk-hidden@l to hidden the toogle on desktop and visible on mobile/tablet devices'),
                'depends' => array(
                  array('type', '=', 'uk-navbar-nav'),
                  array('responsive_menu' => '1')
                ),
            ),
            'right_menu' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Right Toggle Menu'),
                'desc' => \Joomla\CMS\Language\Text::_('Assign the toggle menu icon to the right position'),
                'std' => 0,
                'depends' => array(
                  array('type', '=', 'uk-navbar-nav'),
                  array('responsive_menu' => '1')
                ),
            ),
            'flip' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Flip Offcanvas'),
                'desc' => \Joomla\CMS\Language\Text::_('Choose this option to adjust its alignment, so that it slides in from the right.'),
                'values' => array(
                    1 => \Joomla\CMS\Language\Text::_('JYES'),
                    0 => \Joomla\CMS\Language\Text::_('JNO'),
                ),
                'std' => 0,
                'depends' => array(
                  array('type', '=', 'uk-navbar-nav'),
                  array('responsive_menu' => '1')
                ),
            ),
            'sticky_menu' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Enable Navbar Sticky'),
                'desc' => \Joomla\CMS\Language\Text::_('Make elements remain at the top of the viewport, like a sticky navigation.'),
                'std' => 0,
            ),
            'transparent_menu' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Transparent Navbar'),
                'std' => 0,
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'scroll_to' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Scroll smoothly'),
                'desc' => \Joomla\CMS\Language\Text::_('Scroll smoothly when jumping to different sections on a page.'),
                'std' => 0,
            ),
            'scroll_offset' => array(
                'type' => 'number',
                'title' => \Joomla\CMS\Language\Text::_('Pixel offset added to scroll top.'),
                'std' => 90,
                'depends' => array('scroll_to' => '1'),
            ),

            'card_style' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Card Style'),
                'desc' => \Joomla\CMS\Language\Text::_('UIkit includes a number of modifiers that can be used to add a specific style to cards.'),
                'values' => array(
                    'uk-card-default' => \Joomla\CMS\Language\Text::_('Card Default'),
                    'uk-card-primary' => \Joomla\CMS\Language\Text::_('Card Primary'),
                    'uk-card-secondary' => \Joomla\CMS\Language\Text::_('Card Secondary'),
                ),
                'std' => 'uk-card-default',
                'depends' => array(array('type', '!=', 'uk-navbar-nav')),
            ),
            'card_size' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Card Size'),
                'desc' => \Joomla\CMS\Language\Text::_('You can apply different size modifiers to cards that will decrease or increase their padding.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'uk-card-small' => \Joomla\CMS\Language\Text::_('Small'),
                    'uk-card-large' => \Joomla\CMS\Language\Text::_('Large'),
                ),
                'std' => '',
                'depends' => array(array('type', '!=', 'uk-navbar-nav')),
            ),
            'hover' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Hover'),
                'desc' => \Joomla\CMS\Language\Text::_('This comes in handy when working with anchors and can be combined with the other card modifiers.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('No'),
                    'uk-card-hover' => \Joomla\CMS\Language\Text::_('Yes'),
                ),
                'depends' => array(array('type', '!=', 'uk-navbar-nav')),
            ),
            'label_text' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('Label'),
                'desc' => \Joomla\CMS\Language\Text::_('Easily create nice looking notification badges.'),
                'std' => '',
                'depends' => array(array('type', '!=', 'uk-navbar-nav')),
            ),
            'label_styles' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Label Style'),
                'desc' => \Joomla\CMS\Language\Text::_('Indicate important notes and highlight parts of your content.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'uk-label-success' => \Joomla\CMS\Language\Text::_('Success'),
                    'uk-label-warning' => \Joomla\CMS\Language\Text::_('Warning'),
                    'uk-label-danger' => \Joomla\CMS\Language\Text::_('Danger'),
                ),
                'depends' => array(array('type', '!=', 'uk-navbar-nav')),
            ),
            'align' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Menu Alignment'),
                'desc' => \Joomla\CMS\Language\Text::_('Add one of these option to align the navigation.'),
                'values' => array(
                    'left' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LEFT'),
                    'right' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_RIGHT'),
                    'center' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_CENTER'),
                ),
                'std' => 'left'
            ),
            'item_dropdown_style' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Dropdown Options'),
                'desc' => \Joomla\CMS\Language\Text::_('A navbar can contain a dropdown, you need to enable dropdown feature for item first before using the options below.'),
            ),
            'enable_dropbar' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Enable Dropbar'),
                'desc' => \Joomla\CMS\Language\Text::_('A dropbar extends to the full width of the navbar and displays the dropdown without its default styling.'),
                'std' => 0,
            ),
            'enable_boundary' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Boundary'),
                'desc' => \Joomla\CMS\Language\Text::_('Dropdowns can be aligned to the navbar\'s boundary. By default, dropdowns are aligned to the left.'),
                'std' => 0,
            ),
            'boundary_alignment' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Boundary alignment'),
                'values' => array(
                    'left' => \Joomla\CMS\Language\Text::_('Left'),
                    'right' => \Joomla\CMS\Language\Text::_('Right'),
                    'center' => \Joomla\CMS\Language\Text::_('Center'),
                ),
                'std' => 'left',
                'depends' => array('enable_boundary' => '1'),
            ),
            'navbar_style' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Navbar'),
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),

            'nav_style' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Nav Style'),
                'depends' => array(array('type', '=', 'uk-nav uk-nav-default')),
            ),
            'text_transform' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Title transform'),
                'desc' => \Joomla\CMS\Language\Text::_('The following options will transform title into uppercased, capitalized or lowercased characters.'),
                'values' => array(
                    '' => 'Inherit',
                    'uppercase' => 'Uppercase',
                    'capitalize' => 'Capitalize',
                    'lowercase' => 'Lowercase',
                ),
                'std' => '',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'nav_bg' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Nav Background'),
                'std' => '#f8f8f8',
                'depends' => array(array('type', '=', 'uk-nav uk-nav-default')),
            ),

            'nav_fontsize' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Nav Font Size'),
                'std' => '',
                'max' => 200,
                'depends' => array(array('type', '=', 'uk-nav uk-nav-default')),
            ),
            'nav_item_color' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Nav Color'),
                'std' => '#999999',
                'depends' => array(array('type', '=', 'uk-nav uk-nav-default')),
            ),
            'nav_item_color_active' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Nav Hover/Active Color'),
                'std' => '#666666',
                'depends' => array(array('type', '=', 'uk-nav uk-nav-default')),
            ),

            'navbar_bg' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Navbar Background'),
                'std' => '#f8f8f8',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'navbar_item_color' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Navbar Color'),
                'std' => '#999999',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'navbar_item_color_active' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Navbar Hover/Active Color'),
                'std' => '#666666',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'toggle_color' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Toggle Color Item'),
                'std' => '#999999',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'toggle_color_active' => array(
                'type' => 'color',
                'title' => \Joomla\CMS\Language\Text::_('Toggle Active Color'),
                'std' => '#666666',
                'depends' => array(array('type', '=', 'uk-navbar-nav')),
            ),
            'separator_general_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('General'),
            ),
            'addon_margin' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Margin'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the vertical margin. Note: The first element\'s top margin and the last element\'s bottom margin are always removed. Define those in the grid settings instead.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Keep existing'),
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'default' => \Joomla\CMS\Language\Text::_('Default'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                    'xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    'remove-vertical' => \Joomla\CMS\Language\Text::_('None'),
                ),
                'std' => '',
            ),
            'addon_max_width' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Max Width'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the maximum content width.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                    'xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    '2xlarge' => \Joomla\CMS\Language\Text::_('2X-Large'),
                ),
                'std' => '',
            ),
            'addon_max_width_breakpoint' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Max Width Breakpoint'),
                'desc' => \Joomla\CMS\Language\Text::_('Define the device width from which the element\'s max-width will apply.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    's' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std' => '',
                'depends' => array(array('addon_max_width', '!=', '')),
            ),
            'block_align'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the alignment in case the container exceeds the element\'s max-width.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Left'),
                    'center'=>\Joomla\CMS\Language\Text::_('Center'),
                    'right'=>\Joomla\CMS\Language\Text::_('Right'),
                ),
                'std'=>'',
                'depends'=>array(array('addon_max_width', '!=', '')),
            ),
            'block_align_breakpoint'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment Breakpoint'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the device width from which the alignment will apply.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Always'),
                    's'=>\Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'm'=>\Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'l'=>\Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl'=>\Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std'=>'',
                'depends'=>array(array('addon_max_width', '!=', '')),
            ),
            'block_align_fallback'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment Fallback'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the alignment in case the container exceeds the element\'s max-width.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Left'),
                    'center'=>\Joomla\CMS\Language\Text::_('Center'),
                    'right'=>\Joomla\CMS\Language\Text::_('Right'),
                ),
                'std'=>'',
                'depends'=>array(
                  array('addon_max_width', '!=', ''),
                  array('block_align_breakpoint', '!=', '')
                ),
            ),
            'alignment' => array(
              'type' => 'select',
              'title' => \Joomla\CMS\Language\Text::_('Text Alignment'),
              'desc' => \Joomla\CMS\Language\Text::_('Center, left and right alignment.'),
              'values' => array(
                  '' => \Joomla\CMS\Language\Text::_('Inherit'),
                  'uk-text-left' => \Joomla\CMS\Language\Text::_('Left'),
                  'uk-text-center' => \Joomla\CMS\Language\Text::_('Center'),
                  'uk-text-right' => \Joomla\CMS\Language\Text::_('Right'),
                  'uk-text-justify' => \Joomla\CMS\Language\Text::_('Justify'),
              ),
              'std' => '',
            ),
          'text_breakpoint' => array(
              'type' => 'select',
              'title' => \Joomla\CMS\Language\Text::_('Text Alignment Breakpoint'),
              'desc' => \Joomla\CMS\Language\Text::_('Display the text alignment only on this device width and larger'),
              'values' => array(
                  '' => \Joomla\CMS\Language\Text::_('Always'),
                  's' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                  'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                  'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                  'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
              ),
              'std' => '',
              'depends' => array(array('alignment', '!=', '')),
            ),
          'text_alignment_fallback' => array(
              'type' => 'select',
              'title' => \Joomla\CMS\Language\Text::_('Text Alignment Fallback'),
              'desc' => \Joomla\CMS\Language\Text::_('Define an alignment fallback for device widths below the breakpoint'),
              'values' => array(
                  '' => \Joomla\CMS\Language\Text::_('Inherit'),
                  'left' => \Joomla\CMS\Language\Text::_('Left'),
                  'center' => \Joomla\CMS\Language\Text::_('Center'),
                  'right' => \Joomla\CMS\Language\Text::_('Right'),
                  'justify' => \Joomla\CMS\Language\Text::_('Justify'),
              ),
              'std' => '',
              'depends' => array(
                array('text_breakpoint', '!=', ''),
                array('alignment', '!=', '')
              ),
            ),
            'animation' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Animation'),
                'desc' => \Joomla\CMS\Language\Text::_('A collection of smooth animations to use within your page.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Inherit'),
                    'fade' => \Joomla\CMS\Language\Text::_('Fade'),
                    'scale-up' => \Joomla\CMS\Language\Text::_('Scale Up'),
                    'scale-down' => \Joomla\CMS\Language\Text::_('Scale Down'),
                    'slide-top-small' => \Joomla\CMS\Language\Text::_('Slide Top Small'),
                    'slide-bottom-small' => \Joomla\CMS\Language\Text::_('Slide Bottom Small'),
                    'slide-left-small' => \Joomla\CMS\Language\Text::_('Slide Left Small'),
                    'slide-right-small' => \Joomla\CMS\Language\Text::_('Slide Right Small'),
                    'slide-top-medium' => \Joomla\CMS\Language\Text::_('Slide Top Medium'),
                    'slide-bottom-medium' => \Joomla\CMS\Language\Text::_('Slide Bottom Medium'),
                    'slide-left-medium' => \Joomla\CMS\Language\Text::_('Slide Left Medium'),
                    'slide-right-medium' => \Joomla\CMS\Language\Text::_('Slide Right Medium'),
                    'slide-top' => \Joomla\CMS\Language\Text::_('Slide Top 100%'),
                    'slide-bottom' => \Joomla\CMS\Language\Text::_('Slide Bottom 100%'),
                    'slide-left' => \Joomla\CMS\Language\Text::_('Slide Left 100%'),
                    'slide-right' => \Joomla\CMS\Language\Text::_('Slide Right 100%'),
                    'parallax' => \Joomla\CMS\Language\Text::_('Parallax'),
                ),
                'std' => '',
            ),
            'animation_repeat' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Repeat Animation'),
                'desc' => \Joomla\CMS\Language\Text::_('Applies the animation class every time the element is in view'),
                'std' => 0,
                'depends' => array(
                  array('animation', '!=', ''),
                  array('animation', '!=', 'parallax'),
                ),
            ),
            'separator_parallax_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Parallax Animation Settings'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'horizontal_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Horizontal Start'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the horizontal position (translateX) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'horizontal_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Horizontal End'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the horizontal position (translateX) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'vertical_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Vertical Start'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the vertical position (translateY) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'vertical_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Vertical End'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the vertical position (translateY) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'scale_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Scale Start'),
                'min' => 50,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the scaling. Min: 50, Max: 200 =>  100 means 100% scale, 200 means 200% scale, and 50 means 50% scale.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'scale_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Scale End'),
                'min' => 50,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the scaling. Min: 50, Max: 200 =>  100 means 100% scale, 200 means 200% scale, and 50 means 50% scale.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'rotate_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Rotate Start'),
                'min' => 0,
                'max' => 360,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the rotation clockwise in degrees.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'rotate_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Rotate End'),
                'min' => 0,
                'max' => 360,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the rotation clockwise in degrees.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'opacity_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Opacity Start'),
                'min' => 0,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the opacity. 100 means 100% opacity, and 0 means 0% opacity.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'opacity_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Opacity End'),
                'min' => 0,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the opacity. 100 means 100% opacity, and 0 means 0% opacity.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'easing' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Easing'),
                'min' => -200,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Set the animation easing. A value below 100 is faster in the beginning and slower towards the end while a value above 100 behaves inversely.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'viewport' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Viewport'),
                'min' => 10,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Set the animation end point relative to viewport height, e.g. 50 for 50% of the viewport'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'parallax_target' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Target'),
                'desc' => \Joomla\CMS\Language\Text::_('Animate the element as long as the section is visible.'),
                'std' => 0,
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'parallax_zindex' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Z Index'),
                'desc' => \Joomla\CMS\Language\Text::_('Set a higher stacking order.'),
                'std' => 0,
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'breakpoint' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Breakpoint'),
                'desc' => \Joomla\CMS\Language\Text::_('Display the parallax effect only on this device width and larger. It is useful to disable the parallax animation on small viewports.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    's' => \Joomla\CMS\Language\Text::_('Small (Phone)'),
                    'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet)'),
                    'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std' => '',
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'visibility' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Visibility'),
                'desc' => \Joomla\CMS\Language\Text::_('Display the element only on this device width and larger.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    'uk-visible@s' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'uk-visible@m' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'uk-visible@l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'uk-visible@xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                    'uk-hidden@s' => \Joomla\CMS\Language\Text::_('Hidden Small (Phone Landscape)'),
                    'uk-hidden@m' => \Joomla\CMS\Language\Text::_('Hidden Medium (Tablet Landscape)'),
                    'uk-hidden@l' => \Joomla\CMS\Language\Text::_('Hidden Large (Desktop)'),
                    'uk-hidden@xl' => \Joomla\CMS\Language\Text::_('Hidden X-Large (Large Screens)'),
                ),
                'std' => '',
            ),
            'class' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_CLASS'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_CLASS_DESC'),
                'std' => '',
            ),
          )
      )
    )
);
