<?php

/**
 * @package Jollyany Addons SP Page Builder
 * @author TemPlaza https://templaza.com
 * @copyright Copyright (c) 2011 - 2021 TemPlaza
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or later
 */
//no direct accees
defined('_JEXEC') or die('restricted aceess');
SpAddonsConfig::addonConfig(
    array(
      'type' => 'general',
      'addon_name' => 'uibutton',
      'title' => \Joomla\CMS\Language\Text::_('UI Button'),
      'desc' => \Joomla\CMS\Language\Text::_('Easily create nice looking buttons, which come in different styles.'),
      'icon'=>\Joomla\CMS\Uri\Uri::root() . 'plugins/sppagebuilder/jollyany/addons/uibutton/assets/images/icon.png',
      'category' => 'Jollyany',
      'attr' => array(
          'general' => array(
            'admin_label' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_ADMIN_LABEL'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_ADMIN_LABEL_DESC'),
                'std' => '',
            ),
            'title_addon' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('Title'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_TITLE_DESC'),
                'std' =>  '',
            ),
            'title_heading_style' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Style'),
                'desc' => \Joomla\CMS\Language\Text::_('Heading styles differ in font-size but may also come with a predefined color, size and font'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'heading-2xlarge' => \Joomla\CMS\Language\Text::_('2XLarge'),
                    'heading-xlarge' => \Joomla\CMS\Language\Text::_('XLarge'),
                    'heading-large' => \Joomla\CMS\Language\Text::_('Large'),
                    'heading-medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'heading-small' => \Joomla\CMS\Language\Text::_('Small'),
                    'h1' => \Joomla\CMS\Language\Text::_('H1'),
                    'h2' => \Joomla\CMS\Language\Text::_('H2'),
                    'h3' => \Joomla\CMS\Language\Text::_('H3'),
                    'h4' => \Joomla\CMS\Language\Text::_('H4'),
                    'h5' => \Joomla\CMS\Language\Text::_('H5'),
                    'h6' => \Joomla\CMS\Language\Text::_('H6'),
                ),
                'std' => 'h3',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_margin' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Title Margin'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the vertical margin for title.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Keep existing'),
                    'uk-margin-small' => \Joomla\CMS\Language\Text::_('Small'),
                    'uk-margin' => \Joomla\CMS\Language\Text::_('Default'),
                    'uk-margin-medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'uk-margin-large' => \Joomla\CMS\Language\Text::_('Large'),
                    'uk-margin-xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    'uk-margin-remove-vertical' => \Joomla\CMS\Language\Text::_('None'),
                ),
                'std' => 'uk-margin',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_decoration' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Decoration'),
                'desc' => \Joomla\CMS\Language\Text::_('Decorate the heading with a divider, bullet or a line that is vertically centered to the heading'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'uk-heading-divider' => \Joomla\CMS\Language\Text::_('Divider'),
                    'uk-heading-bullet' => \Joomla\CMS\Language\Text::_('Bullet'),
                    'uk-heading-line' => \Joomla\CMS\Language\Text::_('Line'),
                ),
                'std' => '',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_color' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Color'),
                'desc' => \Joomla\CMS\Language\Text::_('Select the text color. If the Background option is selected, styles that don\'t apply a background image use the primary color instead.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'text-muted' => \Joomla\CMS\Language\Text::_('Muted'),
                    'text-emphasis' => \Joomla\CMS\Language\Text::_('Emphasis'),
                    'text-primary' => \Joomla\CMS\Language\Text::_('Primary'),
                    'text-secondary' => \Joomla\CMS\Language\Text::_('Secondary'),
                    'text-success' => \Joomla\CMS\Language\Text::_('Success'),
                    'text-warning' => \Joomla\CMS\Language\Text::_('Warning'),
                    'text-danger' => \Joomla\CMS\Language\Text::_('Danger'),
                ),
                'std' => '',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'title_heading_selector' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('HTML Element'),
                'desc' => \Joomla\CMS\Language\Text::_('Choose one of the seven heading elements to fit your semantic structure.'),
                'values' => array(
                    'h1' => \Joomla\CMS\Language\Text::_('h1'),
                    'h2' => \Joomla\CMS\Language\Text::_('h2'),
                    'h3' => \Joomla\CMS\Language\Text::_('h3'),
                    'h4' => \Joomla\CMS\Language\Text::_('h4'),
                    'h5' => \Joomla\CMS\Language\Text::_('h5'),
                    'h6' => \Joomla\CMS\Language\Text::_('h6'),
                    'div' => \Joomla\CMS\Language\Text::_('div'),
                ),
                'std' => 'h3',
                'depends' => array(array('title_addon', '!=', '')),
            ),
            'ui_list_buttons' => array(
              'title' => \Joomla\CMS\Language\Text::_('Items'),
              'attr' =>  array(
                'button_title' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('Content'),
                    'std' => 'Learn More',
                ),
                'link' => array(
                    'type' => 'media',
                    'format' => 'attachment',
                    'title' => \Joomla\CMS\Language\Text::_('Link'),
                    'desc' => \Joomla\CMS\Language\Text::_('Enter or pick a link, an image or a video file.'),
                    'placeholder' => 'http://',
                    'hide_preview' => true,
                ),
                'link_title' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('Link Title'),
                    'desc' => \Joomla\CMS\Language\Text::_('Enter an optional text for the title attribute of the link, which will appear on hover.'),
                ),
                'target' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LINK_NEWTAB'),
                    'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LINK_NEWTAB_DESC'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET_SAME_WINDOW'),
                        '_blank' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_GLOBAL_TARGET_NEW_WINDOW'),
                    ),
                    'depends' => array(array('link', '!=', '')),
                ),
                'icon_type' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Icon Type'),
                    'desc' => \Joomla\CMS\Language\Text::_('Select icon type from the list'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('FontAwesome'),
                        'uikit' => \Joomla\CMS\Language\Text::_('Uikit'),
                        'custom' => \Joomla\CMS\Language\Text::_('Custom'),
                    ),
                    'std' => '',
                ),
                'btn_icon' => array(
                    'type' => 'icon',
                    'title' => \Joomla\CMS\Language\Text::_('Icon'),
                    'depends' => array(
                      array('icon_type', '!=', 'uikit'),
                      array('icon_type', '!=', 'custom')
                    ),
                ),
                'custom_icon' => array(
                    'type' => 'text',
                    'title' => \Joomla\CMS\Language\Text::_('Icon Class Name'),
                    'placeholder' => 'flaticon-check',
                    'depends' => array(
                      array('icon_type', '=', 'custom'),
                    ),
                ),
                'uikit_icon' => array( // New Uikit Icon
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Uikit Icon'),
                    'desc' => \Joomla\CMS\Language\Text::_('Select an SVG icon from the list. Learn more <a href="https://getuikit.com/docs/icon#library" target="_blank">https://getuikit.com/docs/icon</a>'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('Select an optional icon.'),
                        'home' => 'Home',
                        'sign-in' => 'Sign-in',
                        'sign-out' => 'Sign-out',
                        'user' => 'User',
                        'users' => 'Users',
                        'lock' => 'Lock',
                        'unlock' => 'Unlock',
                        'settings' => 'Settings',
                        'cog' => 'Cog',
                        'nut' => 'Nut',
                        'comment' => 'Comment',
                        'commenting' => 'Commenting',
                        'comments' => 'Comments',
                        'hashtag' => 'Hashtag',
                        'tag' => 'Tag',
                        'cart' => 'Cart',
                        'credit-card' => 'Credit-card',
                        'mail' => 'Mail',
                        'receiver' => 'Receiver',
                        'search' => 'Search',
                        'location' => 'Location',
                        'bookmark' => 'Bookmark',
                        'code' => 'Code',
                        'paint-bucket' => 'Paint-bucket',
                        'camera' => 'Camera',
                        'bell' => 'Bell',
                        'bolt' => 'Bolt',
                        'star' => 'Star',
                        'heart' => 'Heart',
                        'happy' => 'Happy',
                        'lifesaver' => 'Lifesaver',
                        'rss' => 'Rss',
                        'social' => 'Social',
                        'git-branch' => 'Git-branch',
                        'git-fork' => 'Git-fork',
                        'world' => 'World',
                        'calendar' => 'Calendar',
                        'clock' => 'Clock',
                        'history' => 'History',
                        'future' => 'Future',
                        'pencil' => 'Pencil',
                        'trash' => 'Trash',
                        'move' => 'Move',
                        'link' => 'Link',
                        'question' => 'Question',
                        'info' => 'Info',
                        'warning' => 'Warning',
                        'image' => 'Image',
                        'thumbnails' => 'Thumbnails',
                        'table' => 'Table',
                        'list' => 'List',
                        'menu' => 'Menu',
                        'grid' => 'Grid',
                        'more' => 'More',
                        'more-vertical' => 'More-vertical',
                        'plus' => 'Plus',
                        'plus-circle' => 'Plus-circle',
                        'minus' => 'Minus',
                        'minus-circle' => 'Minus-circle',
                        'close' => 'Close',
                        'check' => 'Check',
                        'ban' => 'Ban',
                        'refresh' => 'Refresh',
                        'play' => 'Play',
                        'play-circle' => 'Play-circle',
                        'tv' => 'Tv',
                        'desktop' => 'Desktop',
                        'laptop' => 'Laptop',
                        'tablet' => 'Tablet',
                        'phone' => 'Phone',
                        'tablet-landscape' => 'Tablet-landscape',
                        'phone-landscape' => 'Phone-landscape',
                        'file' => 'File',
                        'copy' => 'Copy',
                        'file-edit' => 'File-edit',
                        'folder' => 'Folder',
                        'album' => 'Album',
                        'push' => 'Push',
                        'pull' => 'Pull',
                        'server' => 'Server',
                        'database' => 'Database',
                        'cloud-upload' => 'Cloud-upload',
                        'cloud-download' => 'Cloud-download',
                        'download' => 'Download',
                        'upload' => 'Upload',
                        'reply' => 'Reply',
                        'forward' => 'Forward',
                        'expand' => 'Expand',
                        'shrink' => 'Shrink',
                        'arrow-up' => 'Arrow-up',
                        'arrow-down' => 'Arrow-down',
                        'arrow-left' => 'Arrow-left',
                        'arrow-right' => 'Arrow-right',
                        'chevron-up' => 'Chevron-up',
                        'chevron-down' => 'Chevron-down',
                        'chevron-left' => 'Chevron-left',
                        'chevron-right' => 'Chevron-right',
                        'triangle-up' => 'Triangle-up',
                        'triangle-down' => 'Triangle-down',
                        'triangle-left' => 'Triangle-left',
                        'triangle-right' => 'Triangle-right',
                        'bold' => 'Bold',
                        'italic' => 'Italic',
                        'strikethrough' => 'Strikethrough',
                        'video-camera' => 'Video-camera',
                        'quote-right' => 'Quote-right',
                        '500px' => '500px',
                        'behance' => 'Behance',
                        'dribbble' => 'Dribbble',
                        'facebook' => 'Facebook',
                        'flickr' => 'Flickr',
                        'foursquare' => 'Foursquare',
                        'github' => 'Github',
                        'github-alt' => 'Github-alt',
                        'gitter' => 'Gitter',
                        'google' => 'Google',
                        'google-plus' => 'Google-plus',
                        'instagram' => 'Instagram',
                        'joomla' => 'Joomla',
                        'linkedin' => 'Linkedin',
                        'pagekit' => 'Pagekit',
                        'pinterest' => 'Pinterest',
                        'soundcloud' => 'Soundcloud',
                        'tripadvisor' => 'Tripadvisor',
                        'tumblr' => 'Tumblr',
                        'twitter' => 'Twitter',
                        'uikit' => 'Uikit',
                        'etsy' => 'Etsy',
                        'vimeo' => 'Vimeo',
                        'whatsapp' => 'Whatsapp',
                        'wordpress' => 'Wordpress',
                        'xing' => 'Xing',
                        'yelp' => 'Yelp',
                        'youtube' => 'Youtube',
                        'print' => 'Print',
                        'reddit' => 'Reddit',
                        'file-text' => 'File Text',
                        'file-pdf' => 'File Pdf',
                        'chevron-double-left' => 'Chevron Double Left',
                        'chevron-double-right' => 'Chevron Double Right',
                    ),
                    'std' => 'check',
                    'depends' => array(
                      array('icon_type', '=', 'uikit'),
                    ),
                ),
                'icon_position' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Icon Alignment'),
                    'desc' => \Joomla\CMS\Language\Text::_('Choose the icon position.'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_LEFT'),
                        'right' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_RIGHT'),
                    ),
                    'std' => '',
                    'depends' => array(array('btn_icon', '!=', '')),
                ),
                'button_style' => array(
                    'type' => 'select',
                    'title' => \Joomla\CMS\Language\Text::_('Style'),
                    'desc' => \Joomla\CMS\Language\Text::_('Set the button style.'),
                    'values' => array(
                        '' => \Joomla\CMS\Language\Text::_('Default'),
                        'primary' => \Joomla\CMS\Language\Text::_('Primary'),
                        'secondary' => \Joomla\CMS\Language\Text::_('Secondary'),
                        'danger' => \Joomla\CMS\Language\Text::_('Danger'),
                        'text' => \Joomla\CMS\Language\Text::_('Text'),
                        'link' => \Joomla\CMS\Language\Text::_('Link'),
                        'link-muted' => \Joomla\CMS\Language\Text::_('Link Muted'),
                        'link-text' => \Joomla\CMS\Language\Text::_('Link Text'),
                        'custom' => \Joomla\CMS\Language\Text::_('Custom'),
                    ),
                    'std' => '',
                ),
                  'button_shape' => array(
                      'type' => 'select',
                      'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_BUTTON_SHAPE'),
                      'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_BUTTON_SHAPE_DESC'),
                      'values' => array(
                          'rounded' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_BUTTON_SHAPE_ROUNDED'),
                          'square' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_BUTTON_SHAPE_SQUARE'),
                          'round' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_GLOBAL_BUTTON_SHAPE_ROUND'),
                      ),
                      'depends' => array(
                          array('button_style', '!=', 'link'),
                          array('button_style', '!=', 'link-muted'),
                          array('button_style', '!=', 'link-text'),
                          array('button_style', '!=', 'text'),
                      )
                  ),
                'separator_button_custom_options' => array(
                    'type' => 'separator',
                    'title' => \Joomla\CMS\Language\Text::_('Custom Button Style'),
                    'depends' => array(
                      array('button_style', '=', 'custom'),
                    )
                ),
                'button_background' => array(
                    'type' => 'color',
                    'title' => \Joomla\CMS\Language\Text::_('Background Color'),
                    'std' => '#1e87f0',
                    'depends' => array(
                      array('button_style', '=', 'custom'),
                    )
                ),
                'button_color' => array(
                    'type' => 'color',
                    'title' => \Joomla\CMS\Language\Text::_('Button Color'),
                    'depends' => array(
                      array('button_style', '=', 'custom'),
                    )
                ),
                'button_background_hover' => array(
                    'type' => 'color',
                    'title' => \Joomla\CMS\Language\Text::_('Hover Background Color'),
                    'std' => '#1e87f0',
                    'depends' => array(
                      array('button_style', '=', 'custom'),
                    )
                ),
                'button_hover_color' => array(
                    'type' => 'color',
                    'title' => \Joomla\CMS\Language\Text::_('Hover Button Color'),
                    'depends' => array(
                      array('button_style', '=', 'custom'),
                    )
                ),
              ),
            ),
            'separator_misc_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Misc Settings'),
            ),
            'font_weight' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Font weight'),
                'desc' => \Joomla\CMS\Language\Text::_('Add one of the following classes to modify the font weight of your text.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'light' => \Joomla\CMS\Language\Text::_('Light'),
                    'normal' => \Joomla\CMS\Language\Text::_('Normal'),
                    'bold' => \Joomla\CMS\Language\Text::_('Bold'),
                    'lighter' => \Joomla\CMS\Language\Text::_('Lighter'),
                    'bolder' => \Joomla\CMS\Language\Text::_('Bolder'),
                ),
            ),
            'button_size' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Button Size'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the size for multiple buttons.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                ),
            ),
            'grid_width' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Full width button'),
                'std' => 0,
            ),
            'grid_column_gap' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Column Gap'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the size of the column gap between multiple buttons.'),
                'values' => array(
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                ),
                'std' => 'small',
            ),
            'grid_row_gap' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Row Gap'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the size of the row gap between multiple buttons.'),
                'values' => array(
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    '' => \Joomla\CMS\Language\Text::_('Default'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                ),
                'std' => 'small',
            ),
            'separator_button_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('General'),
            ),
            'addon_margin' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Margin'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the vertical margin. Note: The first element\'s top margin and the last element\'s bottom margin are always removed. Define those in the grid settings instead.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Keep existing'),
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'default' => \Joomla\CMS\Language\Text::_('Default'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                    'xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    'remove-vertical' => \Joomla\CMS\Language\Text::_('None'),
                ),
                'std' => '',
            ),
            'addon_max_width' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Max Width'),
                'desc' => \Joomla\CMS\Language\Text::_('Set the maximum content width.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'small' => \Joomla\CMS\Language\Text::_('Small'),
                    'medium' => \Joomla\CMS\Language\Text::_('Medium'),
                    'large' => \Joomla\CMS\Language\Text::_('Large'),
                    'xlarge' => \Joomla\CMS\Language\Text::_('X-Large'),
                    '2xlarge' => \Joomla\CMS\Language\Text::_('2X-Large'),
                ),
                'std' => '',
            ),
            'addon_max_width_breakpoint' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Max Width Breakpoint'),
                'desc' => \Joomla\CMS\Language\Text::_('Define the device width from which the element\'s max-width will apply.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    's' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std' => '',
                'depends' => array(array('addon_max_width', '!=', '')),
            ),
            'block_align'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the alignment in case the container exceeds the element\'s max-width.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Left'),
                    'center'=>\Joomla\CMS\Language\Text::_('Center'),
                    'right'=>\Joomla\CMS\Language\Text::_('Right'),
                ),
                'std'=>'',
                'depends'=>array(array('addon_max_width', '!=', '')),
            ),
            'block_align_breakpoint'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment Breakpoint'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the device width from which the alignment will apply.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Always'),
                    's'=>\Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'm'=>\Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'l'=>\Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl'=>\Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std'=>'',
                'depends'=>array(array('addon_max_width', '!=', '')),
            ),
            'block_align_fallback'=>array(
                'type'=>'select',
                'title'=>\Joomla\CMS\Language\Text::_('Block Alignment Fallback'),
                'desc'=>\Joomla\CMS\Language\Text::_('Define the alignment in case the container exceeds the element\'s max-width.'),
                'values'=>array(
                    ''=>\Joomla\CMS\Language\Text::_('Left'),
                    'center'=>\Joomla\CMS\Language\Text::_('Center'),
                    'right'=>\Joomla\CMS\Language\Text::_('Right'),
                ),
                'std'=>'',
                'depends'=>array(
                    array('addon_max_width', '!=', ''),
                    array('block_align_breakpoint', '!=', '')
                ),
            ),
            'button_alignment' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Text Alignment'),
                'desc' => \Joomla\CMS\Language\Text::_('Center, left and right alignment may depend on a breakpoint and require a fallback.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'left' => \Joomla\CMS\Language\Text::_('Left'),
                    'center' => \Joomla\CMS\Language\Text::_('Center'),
                    'right' => \Joomla\CMS\Language\Text::_('Right'),
                ),
                'std' => '',
            ),
            'button_breakpoint' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Text Alignment Breakpoint'),
                'desc' => \Joomla\CMS\Language\Text::_('Display the button alignment only on this device width and larger'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    's' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std' => '',
                'depends' => array(array('button_alignment', '!=', '')),
            ),
            'button_fallback' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Text Alignment Fallback'),
                'desc' => \Joomla\CMS\Language\Text::_('Define an alignment fallback for device widths below the breakpoint.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('None'),
                    'left' => \Joomla\CMS\Language\Text::_('Left'),
                    'center' => \Joomla\CMS\Language\Text::_('Center'),
                    'right' => \Joomla\CMS\Language\Text::_('Right'),
                ),
                'std' => '',
                'depends' => array(
                  array('button_alignment', '!=', ''),
                  array('button_breakpoint', '!=', '')
                ),
            ),
            'animation' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Animation'),
                'desc' => \Joomla\CMS\Language\Text::_('A collection of smooth animations to use within your page.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Inherit'),
                    'fade' => \Joomla\CMS\Language\Text::_('Fade'),
                    'scale-up' => \Joomla\CMS\Language\Text::_('Scale Up'),
                    'scale-down' => \Joomla\CMS\Language\Text::_('Scale Down'),
                    'slide-top-small' => \Joomla\CMS\Language\Text::_('Slide Top Small'),
                    'slide-bottom-small' => \Joomla\CMS\Language\Text::_('Slide Bottom Small'),
                    'slide-left-small' => \Joomla\CMS\Language\Text::_('Slide Left Small'),
                    'slide-right-small' => \Joomla\CMS\Language\Text::_('Slide Right Small'),
                    'slide-top-medium' => \Joomla\CMS\Language\Text::_('Slide Top Medium'),
                    'slide-bottom-medium' => \Joomla\CMS\Language\Text::_('Slide Bottom Medium'),
                    'slide-left-medium' => \Joomla\CMS\Language\Text::_('Slide Left Medium'),
                    'slide-right-medium' => \Joomla\CMS\Language\Text::_('Slide Right Medium'),
                    'slide-top' => \Joomla\CMS\Language\Text::_('Slide Top 100%'),
                    'slide-bottom' => \Joomla\CMS\Language\Text::_('Slide Bottom 100%'),
                    'slide-left' => \Joomla\CMS\Language\Text::_('Slide Left 100%'),
                    'slide-right' => \Joomla\CMS\Language\Text::_('Slide Right 100%'),
                    'parallax' => \Joomla\CMS\Language\Text::_('Parallax'),
                ),
                'std' => '',
            ),
            'animation_repeat' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Repeat Animation'),
                'desc' => \Joomla\CMS\Language\Text::_('Applies the animation class every time the element is in view'),
                'std' => 0,
                'depends' => array(
                  array('animation', '!=', ''),
                  array('animation', '!=', 'parallax')
                ),
            ),
            'delay_element_animations' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Delay Element Animations'),
                'desc' => \Joomla\CMS\Language\Text::_('Delay element animations so that animations are slightly delayed and don\'t play all at the same time. Slide animations can come into effect with a fixed offset or at 100% of the element\’s own size.'),
                'std' => 0,
                'depends' => array(
                  array('animation', '!=', ''),
                  array('animation', '!=', 'parallax')
                ),
            ),
            'separator_parallax_options' => array(
                'type' => 'separator',
                'title' => \Joomla\CMS\Language\Text::_('Customizing Parallax'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'horizontal_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Horizontal Start'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the horizontal position (translateX) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'horizontal_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Horizontal End'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the horizontal position (translateX) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'vertical_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Vertical Start'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the vertical position (translateY) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'vertical_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Vertical End'),
                'min' => -600,
                'max' => 600,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the vertical position (translateY) in pixels.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'scale_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Scale Start'),
                'min' => 50,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the scaling. Min: 50, Max: 200 =>  100 means 100% scale, 200 means 200% scale, and 50 means 50% scale.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'scale_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Scale End'),
                'min' => 50,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the scaling. Min: 50, Max: 200 =>  100 means 100% scale, 200 means 200% scale, and 50 means 50% scale.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'rotate_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Rotate Start'),
                'min' => 0,
                'max' => 360,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the rotation clockwise in degrees.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'rotate_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Rotate End'),
                'min' => 0,
                'max' => 360,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the rotation clockwise in degrees.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'opacity_start' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Opacity Start'),
                'min' => 0,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the opacity. 100 means 100% opacity, and 0 means 0% opacity.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'opacity_end' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Opacity End'),
                'min' => 0,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Animate the opacity. 100 means 100% opacity, and 0 means 0% opacity.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'easing' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Easing'),
                'min' => -200,
                'max' => 200,
                'desc' => \Joomla\CMS\Language\Text::_('Set the animation easing. A value below 100 is faster in the beginning and slower towards the end while a value above 100 behaves inversely.'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'viewport' => array(
                'type' => 'slider',
                'title' => \Joomla\CMS\Language\Text::_('Viewport'),
                'min' => 10,
                'max' => 100,
                'desc' => \Joomla\CMS\Language\Text::_('Set the animation end point relative to viewport height, e.g. 50 for 50% of the viewport'),
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'parallax_target' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Target'),
                'desc' => \Joomla\CMS\Language\Text::_('Animate the element as long as the section is visible.'),
                'std' => 0,
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'parallax_zindex' => array(
                'type' => 'checkbox',
                'title' => \Joomla\CMS\Language\Text::_('Z Index'),
                'desc' => \Joomla\CMS\Language\Text::_('Set a higher stacking order.'),
                'std' => 0,
                'depends' => array(array('animation', '=', 'parallax')),
            ),
            'breakpoint' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Breakpoint'),
                'desc' => \Joomla\CMS\Language\Text::_('Display the parallax effect only on this device width and larger. It is useful to disable the parallax animation on small viewports.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    's' => \Joomla\CMS\Language\Text::_('Small (Phone)'),
                    'm' => \Joomla\CMS\Language\Text::_('Medium (Tablet)'),
                    'l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                ),
                'std' => '',
                'depends' => array(array('animation', '=', 'parallax')),
            ),

            'visibility' => array(
                'type' => 'select',
                'title' => \Joomla\CMS\Language\Text::_('Visibility'),
                'desc' => \Joomla\CMS\Language\Text::_('Display the element only on this device width and larger.'),
                'values' => array(
                    '' => \Joomla\CMS\Language\Text::_('Always'),
                    'uk-visible@s' => \Joomla\CMS\Language\Text::_('Small (Phone Landscape)'),
                    'uk-visible@m' => \Joomla\CMS\Language\Text::_('Medium (Tablet Landscape)'),
                    'uk-visible@l' => \Joomla\CMS\Language\Text::_('Large (Desktop)'),
                    'uk-visible@xl' => \Joomla\CMS\Language\Text::_('X-Large (Large Screens)'),
                    'uk-hidden@s' => \Joomla\CMS\Language\Text::_('Hidden Small (Phone Landscape)'),
                    'uk-hidden@m' => \Joomla\CMS\Language\Text::_('Hidden Medium (Tablet Landscape)'),
                    'uk-hidden@l' => \Joomla\CMS\Language\Text::_('Hidden Large (Desktop)'),
                    'uk-hidden@xl' => \Joomla\CMS\Language\Text::_('Hidden X-Large (Large Screens)'),
                ),
                'std' => '',
            ),
            'class' => array(
                'type' => 'text',
                'title' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_CLASS'),
                'desc' => \Joomla\CMS\Language\Text::_('COM_SPPAGEBUILDER_ADDON_CLASS_DESC'),
                'std' => '',
            ),
          ),
      ),
    )
);
